### PR TITLE
template-haskell 2.17 compatible & GH Actions CI

### PR DESCRIPTION
**Pull request by sorki**
Follow up to #10

### CODE REVIEW

**Comment by sorki** [comment]
Looks like Actions need to be enabled in Settings.

**Comment by sorki** [comment]
Bumped version as well, should be good for upload.

**Comment by sorki** [comment]
Gentle poke :cat2:

**Comment by UnkindPartition** [comment]
Sorry, let me know your hackage username so that I can add you as an uploader.

**Comment by sorki** [comment]
No problem, it's `srk` - https://hackage.haskell.org/user/srk

**Comment by UnkindPartition** [comment]
Done!

**Pull request merged**
